distance: asks how far apart the two data points are

similarity: how close or related are the two data points

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

students = pd.DataFrame({
    "name": ["Aarav", "Riya", "Kabir", "Meera", "Dev", "Sara"],
    "study_hours": [6, 3, 8, 2, 5, 7],
    "attendance": [85, 70, 90, 60, 78, 92],
    "previous_marks": [78, 55, 88, 35, 65, 84],
    "final_marks": [82, 58, 91, 40, 70, 88]
})


In [ ]:
feature_columns = ["study_hours", "attendance", "previous_marks"]
student_vectors = students[feature_columns].values
print(student_vectors)

[[ 6 85 78]
 [ 3 70 55]
 [ 8 90 88]
 [ 2 60 35]
 [ 5 78 65]
 [ 7 92 84]]


In [ ]:
from natplotlib import MatplotlibDeprecationWarning


In [ ]:
sentence="The movie was not good"
tokens= sentence.lower().split()
print(tokens)

['the', 'movie', 'was', 'not', 'good']


In [ ]:
vocab={
    "the":1,
    "movie":2,
    "was":3,
    "not":4,
    "good":5
}
token_ids=[vocab[word] for word in tokens]
print(token_ids)

[1, 2, 3, 4, 5]


In [ ]:
sentences=[
    "dog bites man",
    "man bites dog",
    "the movie was good",
    "the movie was good not"
    ]
for sentence in sentences:
  print(sentence,"->",sentence.split())

dog bites man -> ['dog', 'bites', 'man']
man bites dog -> ['man', 'bites', 'dog']
the movie was good -> ['the', 'movie', 'was', 'good']
the movie was good not -> ['the', 'movie', 'was', 'good', 'not']


In [1]:
positive_words=["good","great","amazing","excellent","love"]
negative_words=["bad","terrible","poor","hate","boring"]

def simple_sentiment(sentence):
  words=sentence.lower().replace(".","").split()
  score=0

  for word in words:
    if word in positive_words:
      score+=1
    if word in negative_words:
      score-=1

  if score>0:
    return "positive"
  elif score<0:
    return "negative"
  else:
    return "neutral"

print(simple_sentiment("the movie was good"))
print(simple_sentiment("the movie was bad"))
print(simple_sentiment("the movie was not good"))

positive
negative
positive
