In [ ]:
marks=[78,84,62]
avg=sum(marks)/len(marks)
print(avg)

74.66666666666667


In [ ]:
def calculate_average(marks):
  return sum(marks)/len(marks)
student_marks=[78,84,62]
average=calculate_average(student_marks)
print(average)

74.66666666666667


In [ ]:
marks=int(input("enter marks"))
def check(marks):
  if(marks>40):
    print("Pass")
  else:
    print("Fail")

enter marks23


In [ ]:
import numpy as np
marks=np.array([78,84,62])
print(marks +10)

[88 94 72]


In [ ]:
matrix=np.array([
    [1,2,3],
    [4,5,6]
])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
grid=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(grid)
print(grid[1,2])
print(grid[0:2,0:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6
[[1 2]
 [4 5]]


In [ ]:
marks=np.array([78,91,55,72,40,88])
print(marks>70)
high_scores=marks[marks>70]
print(high_scores)

[ True  True False  True False  True]
[78 91 72 88]


In [ ]:
marks=np.array([78,91,55,72,40,88])

print(marks.mean())
print(marks.min())
print(marks.max())
print(marks.sum())

70.66666666666667
40
91
424


In [ ]:
marks = np.array([78,91,55,72,40,88]).reshape(2,3)
print(marks)
print(marks.max())


[[78 91 55]
 [72 40 88]]
91


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving session4_dummy_students_data.csv.xls to session4_dummy_students_data.csv (1).xls


In [ ]:
df["Average"] = df[["math", "science", "english"]].mean(axis=1)

print(df)

    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  Mathura    

In [ ]:
print(df.head)

<bound method NDFrame.head of     student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14        

In [ ]:
top_students = df[df["average"] > 85]

print(top_students)

    student_id    name  age   city  math  science  english  \
1          102    Diya   16  Delhi    91       88       94   
5          106    Sara   16  Delhi    88       93       90   
7          108  Ananya   16  Noida    95       92       89   
13         114   Priya   16  Delhi    89       86       91   
15         116    Riya   16  Noida    92       90       96   

    attendance_percent  study_hours_per_week  assignments_submitted  \
1                   96                    11                     10   
5                   97                    10                     10   
7                   94                    12                     10   
13                  95                    10                     10   
15                  98                    13                     10   

    final_project_score    average result  
1                    93  91.000000   Pass  
5                    95  90.333333   Pass  
7                    91  92.000000   Pass  
13                   92 

In [ ]:
low_attendance = df[df['attendance_percent'] < 75]
print(low_attendance)

    student_id    name  age     city  math  science  english  \
4          105   Rohan   17   Mumbai    40       52       47   
8          109  Vivaan   17   Mumbai    48       57       51   
12         113     Dev   17   Mumbai    35       45       42   
18         119    Yash   17  Mathura    43       49       46   

    attendance_percent  study_hours_per_week  assignments_submitted  \
4                   68                     3                      5   
8                   71                     4                      6   
12                  62                     2                      4   
18                  66                     3                      5   

    final_project_score    average result  
4                    45  46.333333   Pass  
8                    55  52.000000   Pass  
12                   39  40.666667   Pass  
18                   48  46.000000   Pass  


In [ ]:
Mathura = df[df['city'] == "Mathura"]
print(Mathura)

    student_id    name  age     city  math  science  english  \
2          103   Kabir   17  Mathura    55       61       58   
6          107  Ishaan   17  Mathura    64       70       66   
10         111   Arjun   17  Mathura    67       63       72   
14         115   Kunal   17  Mathura    58       54       60   
18         119    Yash   17  Mathura    43       49       46   

    attendance_percent  study_hours_per_week  assignments_submitted  \
2                   75                     5                      6   
6                   82                     6                      7   
10                  80                     6                      8   
14                  77                     5                      6   
18                  66                     3                      5   

    final_project_score    average result  
2                    60  58.000000   Pass  
6                    69  66.666667   Pass  
10                   70  67.333333   Pass  
14          

In [ ]:
df["Result"] = df["average"].apply(lambda x: "Pass" if x >= 40 else "Fail")
print(df)

    student_id    name  age     city  math  science  english  \
0          101   Aarav   16   Mumbai    78       84       69   
1          102    Diya   16    Delhi    91       88       94   
2          103   Kabir   17  Mathura    55       61       58   
3          104   Meera   16    Noida    72       79       81   
4          105   Rohan   17   Mumbai    40       52       47   
5          106    Sara   16    Delhi    88       93       90   
6          107  Ishaan   17  Mathura    64       70       66   
7          108  Ananya   16    Noida    95       92       89   
8          109  Vivaan   17   Mumbai    48       57       51   
9          110    Tara   16    Delhi    83       76       85   
10         111   Arjun   17  Mathura    67       63       72   
11         112   Nisha   16    Noida    74       81       79   
12         113     Dev   17   Mumbai    35       45       42   
13         114   Priya   16    Delhi    89       86       91   
14         115   Kunal   17  Mathura    

In [ ]:
class_avg = df["average"].mean()
print("Class average:", class_avg)

Class average: 71.35000000000001


In [ ]:
print("Highest average:", df["average"].max())
print("Lowest average:", df["average"].min())

Highest average: 92.66666666666667
Lowest average: 40.666666666666664


In [ ]:
top_students = df[df["average"] >= 85]
print("\nTop Students:\n", top_students)


Top Students:
     student_id    name  age   city  math  science  english  \
1          102    Diya   16  Delhi    91       88       94   
5          106    Sara   16  Delhi    88       93       90   
7          108  Ananya   16  Noida    95       92       89   
13         114   Priya   16  Delhi    89       86       91   
15         116    Riya   16  Noida    92       90       96   

    attendance_percent  study_hours_per_week  assignments_submitted  \
1                   96                    11                     10   
5                   97                    10                     10   
7                   94                    12                     10   
13                  95                    10                     10   
15                  98                    13                     10   

    final_project_score    average result Result  
1                    93  91.000000   Pass   Pass  
5                    95  90.333333   Pass   Pass  
7                    91  92.000

In [ ]:
low_attendance = df[df['attendance_percent'] < 75]

print("\nLow Attendance Students:\n", low_attendance)


Low Attendance Students:
     student_id    name  age     city  math  science  english  \
4          105   Rohan   17   Mumbai    40       52       47   
8          109  Vivaan   17   Mumbai    48       57       51   
12         113     Dev   17   Mumbai    35       45       42   
18         119    Yash   17  Mathura    43       49       46   

    attendance_percent  study_hours_per_week  assignments_submitted  \
4                   68                     3                      5   
8                   71                     4                      6   
12                  62                     2                      4   
18                  66                     3                      5   

    final_project_score    average result Result  
4                    45  46.333333   Pass   Pass  
8                    55  52.000000   Pass   Pass  
12                   39  40.666667   Pass   Pass  
18                   48  46.000000   Pass   Pass  


In [ ]:
less_assignments = df[df['assignments_submitted'] < 6]
print("\nLess Assignments Submitted:\n", less_assignments)


Less Assignments Submitted:
     student_id   name  age     city  math  science  english  \
4          105  Rohan   17   Mumbai    40       52       47   
12         113    Dev   17   Mumbai    35       45       42   
18         119   Yash   17  Mathura    43       49       46   

    attendance_percent  study_hours_per_week  assignments_submitted  \
4                   68                     3                      5   
12                  62                     2                      4   
18                  66                     3                      5   

    final_project_score    average result Result  
4                    45  46.333333   Pass   Pass  
12                   39  40.666667   Pass   Pass  
18                   48  46.000000   Pass   Pass  
